name: mushrooms
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_switch: ^0.3.2
  rflutter_alert: ^2.0.4
  syncfusion_flutter_gauges: ^20.2.46
  firebase_database: ^10.2.4
  dropdown_button2: ^1.9.2

dev_dependencies:
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  
flutter:

  uses-material-design: true

  assets:
    - assets/logo.png
    - image/fan.png
    - image/soil_moisture.png